### ISSUE TITLE
can update 1.10？

### ISSUE THREAD

**Issue by mgdgfbhevdyeh** [sdj64/Highlands#30]
i love Highlands.but's looks mod is dead.

**Comment by sdj64** [comment]
Yes, I haven't been active on this in a while.  Sorry but I don't think it will be done.

**Comment by mgdgfbhevdyeh** [comment]
+@sdj64 But a lot of players like Highlands mod.

**Comment by mgdgfbhevdyeh** [comment]
I think most of the players want 1.10.2 or 1.10.

**Comment by mgdgfbhevdyeh** [comment]
I want you to think about it again.

**Comment by mgdgfbhevdyeh** [comment]
closed #30

**Comment by mgdgfbhevdyeh** [comment]
+@sdj64 I want you to think about it again.

**Comment by GuardedAirplane** [comment]
+@sdj64 What would I need to modify in the code to update the mod?

**Comment by sdj64** [comment]
Are you experienced with Forge modding?  I have not loaded it in the Forge workspace for 1.10 so I don't know what's broken.

**Comment by 456Xander** [comment]
@sdj64 I could try porting it to 1.10 if you don't want to. I have some experience with Minecraft Mods.

**Comment by sdj64** [comment]
Go ahead.  I am not really working with Minecraft anymore so you can take over development if you want to.

**Comment by mgdgfbhevdyeh** [comment]
https://github.com/Team-RTG/HighlandsUT
@456Xander
This fork by Team RTG
